### ISSUE TITLE
Problem with or_rviz when launching table_clearing

### ISSUE THREAD

**Issue by stepelle** [personalrobotics/or_rviz#30]
1. I run **rosrun or_rviz test.py**: 
   rviz correctly loads and visualizes the environment. However, the following warning is present
   _[plugindatabase.h:929 _SysLoadLibrary] /home/rosubuntu/ros_ws/devel/share/openrave-0.9/plugins/or_sbpl_plugin.so: /home/rosubuntu/ros_ws/devel/lib/libor_sbpl.so: undefined symbol:
   _ZN4YAML6detail9node_data12empty_scalarE
   [plugindatabase.h:857 _LoadPlugin] failed to load: /home/rosubuntu/ros_ws/devel/share/openrave-0.9/plugins/or_sbpl_plugin.so
   [kinbody.cpp:3232 _ComputeInternalInformation] whiteboard link index 0 has no name
   [kinbody.cpp:3232 _ComputeInternalInformation] whiteboard link index 1 has no name_
2. I run **rosrun table_clearing runHardcodedTask.py --task table_clearing_task --viewSim qtcoin --vision-sim**: 
   everying is correctly shown even if these warnings exist
   
   _[plugindatabase.h:929 _SysLoadLibrary] /home/rosubuntu/ros_ws/devel/share/openrave-0.9/plugins/or_sbpl_plugin.so: /home/rosubuntu/ros_ws/devel/lib/libor_sbpl.so: undefined symbol:
   _ZN4YAML6detail9node_data12empty_scalarE  
   [plugindatabase.h:857 _LoadPlugin] failed to load:
   /home/rosubuntu/ros_ws/devel/share/openrave-0.9/plugins/or_sbpl_plugin.so_
   
   _[ WARN] [1441620093.532895787]: Group 'head_hand' is empty.  
   [kinbody.cpp:1470 SetDOFValues] dof 4 value is not in limits 0.000000e+00<5.235988e-01
   [kinbody.cpp:1470 SetDOFValues] dof 15 value is not in limits 0.000000e+00<5.235988e-01
   [plugindatabase.h:577 Create] Failed to create name SBPL, interface planner
   WARNING: QApplication was not created in the main() thread.
   [plugindatabase.h:577 Create] Failed to create name viewerrecorder, interface module_
3. I run **rosrun table_clearing runHardcodedTask.py --task table_clearing_task --viewSim rviz --vision-sim**: 
   Rviz window opens but nothing is shown (nor the scene or the window buttons). I have the same warnings of point 2 and this error and segmentation fault
   _[kinbody.cpp:3378 _ComputeInternalInformation] failed to set mimic equations on kinematics body herb: openrave (InvalidArguments): [virtual void OpenRAVE::KinBody::Joint::SetMimicEquations(int, const string&, const string&, const string&):1144] failed to set equation '/left/j01_0.321429+0.000000' on herb:/left/j02, at 8. Error is Syntax error: Operator expected*
   _Program received signal SIGSEGV, Segmentation fault.
   0x081270f7 in PyEval_CallObjectWithKeywords ()_
4. I tried to use  on test.py the out-of-process "interactivemarker" mode without
   success. I'm probably doing something wrong. I tried it on test.py. When I
   send some command through the shell, I have a segmentation fault. 

I'm working on 14.04.1-Ubuntu i686.

**Comment by jeking04** [comment]
I have a few ideas.  First, for #1, the `or_sbpl` problem is probably just that you need to download `or_sbpl` into your workspace: https://github.com/personalrobotics/or_sbpl

This will be unrelated to rviz or the crash, but will get rid of the message. You might also need to install `ros-indigo-sbpl` from apt to get or_sbpl to build properly.

We have sometimes seen a crash of or_rviz on 14.04 due to a race condition in initialization.  Could you run this test and see if you still get the crash:

```
cmd> rosrun herbpy console.py --sim --viewer rviz
```

This should load herb in an empty rviz environment. If you see the crash, could you then run:

```
cmd> rosrun herbpy console.py --sim
ipython> env.SetViewer('rviz')
```

And see if you still get the crash.

**Comment by mkoval** [comment]
From the stack trace you sent by email, it looks like you may be missing a few dependencies. If you are on Ubuntu 14.04, then you should be able to [install them via `rosdep`](https://github.com/personalrobotics/pr_docs/wiki/PRL-Development-Environment#installing-dependencies-with-rosdep). If you have not already, you will need [initialize `rosdep` and add our custom configuration to `/etc/ros/rosdep`](https://github.com/personalrobotics/pr_docs/wiki/PRL-Development-Environment#initializing-rosdep) before doing so.

**Comment by mkoval** [comment]
There was also a bug in `interactive_markers` (https://github.com/ros-visualization/interactive_markers/issues/18) that will cause SEGFAULTs in our viewer. This is fixed in the latest version of the code, but it's possible that you have an older version installed. I suggest building `interactive_markers` from source to rule this out:

``` console
$ wstool set interactive_markers https://github.com/ros-visualization/interactive_markers.git --git -v indigo-devel
```

Make sure you source `devel/setup.bash` again after building the library so you are sure you're using the right version.

**Comment by stepelle** [comment]
I downloaded `or_sbpl`from github, substituting the existing version, and the problem was fixed. I run 

```
cmd> rosrun herbpy console.py --sim --viewer rviz
```

and everything worked out. 

The problem related to 

```
rosrun table_clearing runHardcodedTask.py --task table_clearing_task --viewSim rviz --vision-sim
```

was solved by adding a pause in the code: the program crashed before the visualization in rviz was possible. The crash is still there but it seems to be not related to `or_viz` (even if it is not clear to me why it doesn't happen when using qtcoin as visualizer).  

Thank you for the help.
